### ISSUE TITLE
I found two errors in `config-alt.js` 

### ISSUE THREAD

**Issue by TejasLamba2006** [legend-js-dev/anti-alts#1]
```yaml
TypeError: client.parseMs is not a function
    at Object.module.exports.run (/home/container/src/commands/antialt/config-alt.js:47:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async CommandHandler.handle (/home/container/src/handler/command/commandHandler.js:148:4)
TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.module.exports.run (/home/container/src/commands/antialt/config-alt.js:28:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async CommandHandler.handle (/home/container/src/handler/command/commandHandler.js:148:4)
```

**Comment by legend-js-dev** [comment]
This error is caused when you don't extend the client as I did in the source code, the file `Structures/AntiAltClient.js` has the function and it works, you just have to extend the client with the function.

**Comment by TejasLamba2006** [comment]
okh thx
